version=0.1

[default.global.parameters]
stack_name = "glue-reference-implementation"
region = "us-east-1"

[default.deploy.parameters]
fail_on_empty_changeset = "false"
capabilities = "CAPABILITY_IAM"