Transform: AWS::Serverless-2016-10-31
Description: Eample glue project to demonstrate the reference implementation https://github.com/sourceallies/glue-reference-implementation
Resources:
  DataBucket:
    Type: AWS::S3::Bucket

  Database:
    Type: AWS::Glue::Database
    Properties: 
      DatabaseInput: 
        Description: Defines the glue reference datasets
        Name: glue_reference

  # GlueJobRole:
  #   Type: AWS::IAM::Role
  #   Properties:
  #     AssumeRolePolicyDocument:
  #       Statement:
  #         - Effect: Allow
  #           Principal:
  #             Service:
  #               - "glue.amazonaws.com"
  #           Action:
  #             - "sts:AssumeRole"
  #     ManagedPolicyArns:
  #       - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
  #     Policies:
  #       - PolicyName: dataaccess
  #         PolicyDocument:
  #           Statement:
  #             - Effect: Allow
  #               Action:
  #                 - "s3:GetBucketLocation"
  #                 - "s3:GetObject"
  #                 - "s3:ListBucket"
  #                 - "s3:ListBucketMultipartUploads"
  #                 - "s3:ListMultipartUploadParts"
  #                 - "s3:AbortMultipartUpload"
  #                 - "s3:PutObject"
  #                 - "s3:DeleteObject"
  #               Resource:
  #                 - !Sub "arn:aws:s3:::${DataBucket}"
  #                 - !Sub "arn:aws:s3:::${DataBucket}/*"
  #             - Effect: Allow
  #               Action:
  #                 - "s3:GetBucketLocation"
  #                 - "s3:GetObject"
  #                 - "s3:ListBucket"
  #               Resource:
  #                 - "*"

