name: Main Pipeline
on: 
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python3
        uses: actions/setup-python@v3
        with:
          python-version: "3.7"
          cache: "pip"
      
      - name: Run Tests
        run: make run-unit-tests

      - name: Install dependencies
        run: make pip-install

      - name: Check format
        run: make lint

  deploy-aws:
    needs: verify
    runs-on: ubuntu-latest
    concurrency: deploy
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: aws-actions/setup-sam@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: "arn:aws:iam::144406111952:role/Deployer"
          role-session-name: DeployToDevSandbox

      - name: Upload
        run: |
          cd ./src;
          zip -r - ./* | aws s3 cp - "s3://aws-sam-cli-managed-default-samclisourcebucket-9k9zwqsha4fo/etl-files/${GITHUB_SHA}.zip"

      - name: Deploy
        run: |
          sam deploy --parameter-overrides "GitHash=$GITHUB_SHA"

      - name: Upload Sample Data
        run: |
          BUCKET=$(aws cloudformation describe-stack-resources \
            --no-cli-pager \
            --stack-name=glue-reference-implementation \
            --logical-resource-id=DataBucket \
            --query='StackResources[0].PhysicalResourceId' \
            --output=text)
          aws s3 sync \
            --no-cli-pager \
            --delete \
            sample_data "s3://${BUCKET}/sample_data"
