name: Main Pipeline
on: 
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Tests
        run: |
          docker run -it \
          -v "$(pwd):/work" \
          -e DISABLE_SSL=true \
          -e PYTHONPATH='/home/glue_user/aws-glue-libs/PyGlue.zip:/home/glue_user/spark/python/lib/py4j-0.10.9-src.zip:/home/glue_user/spark/python/:/work/src' \
          -w /work \
          --entrypoint=pytest \
          amazon/aws-glue-libs:glue_libs_3.0.0_image_01

  deploy-aws:
    needs: verify
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: aws-actions/setup-sam@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: "arn:aws:iam::144406111952:role/Deployer"
          role-session-name: DeployToDevSandbox

      - name: Deploy
        run: sam deploy

      - name: Upload Sample Data
        run: |
          BUCKET=$(aws cloudformation describe-stack-resources \
            --no-cli-pager \
            --stack-name=glue-reference-implementation \
            --logical-resource-id=DataBucket \
            --query='StackResources[0].PhysicalResourceId' \
            --output=text)
          aws s3 sync \
            --no-cli-pager \
            --delete \
            sample_data "s3://${BUCKET}/sample_data"