name: PR Checks
on:
  push:
    branches-ignore:
      - main

jobs:
  verify:
    name: Verify Code
    runs-on: ubuntu-20.04
    container:
      image: amazon/aws-glue-libs:glue_libs_3.0.0_image_01
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Python3
        uses: actions/setup-python@v3
        with:
          python-version: "3.7"
          cache: "pip"

      - name: Install dependencies
        run: make pip-install

      - name: Lint
        run: make lint

        uses: ./.github/actions/unit-tests
