name: PR Checks
on:
  pull_request:

jobs:
  verify:
    name: Verify Code
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Python3
        uses: actions/setup-python@v3
        with:
          python-version: "3.7"
          cache: "pip"

      - name: Install dependencies
        run: make pip-install

      - name: Lint
        run: make lint

      - name: Run unit tests
        run: make build && make test
