name: Publish to pypi
on: release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup
        run: |
          rm ./src/glue_biscuit/**/test_*.py
          python3 -m pip install --upgrade 'poetry==1.3.1'
          mkdir -p ./dist
          sed -i 's/GH_TAG_NAME/${{ github.event.release.tag_name }}/' ./pyproject.toml

      - name: build
        run: poetry build

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
