name: Publish to pypi
on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup
        run: |
          rm ./src/framework/**/test_*.py
          python3 -m pip install --upgrade 'poetry==1.3.1'
          mkdir -p ./dist
      - name: build
        run: poetry build

      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }} # needs to be added
          repository_url: https://test.pypi.org/legacy/
# NEED to do again with real pypi (do we have a prod account?)
